theme: jekyll-theme-minimal
description: "CEBaB: Estimating the Causal Effects of Real-World Concepts on NLP Model Behavior"
title_image: "https://i.ibb.co/d5bTqrt/Kebab-icon.png"
url: https://cebabing.github.io/CEBaB/